---
published: true
---
The entire state of California experienced a rare confluence of events this past weekend when tropical moisture rode overtop exceptionally strong surface high pressure and triggered widespread dry lightning across much of the state. This unfortunately occurred at the beginning of a prolonged and intense predicted heat wave. Containment efforts on the lightning starts are challenged by the adverse weather and competition for resources.

Given the state's long history of large and damaging fires, as well as the increasing frequency of deadly fires ([3 of the 5 most destructive in State history occurred in the last five years](https://abc7news.com/california-wildfires-fire-update-wildfire-disaster/2516857/)), it might seem odd to call a fire bust like this rare. What sets this situation apart, though, is the natural cause. [Nationwide, 16% of wildfires are caused by lightning, while 95% of California wildfires are human-caused](https://www.latimes.com/california/story/2019-10-29/how-do-wildfires-start). The greater danger in situations like this - especially in California - is the potential for human-caused wildfires to follow the natural surge. Wildland fire management agencies use rating systems to track the availability of resources; according to the [National Interagency Coordination Center](https://gacc.nifc.gov/), the national Preparedness Level is currently 4 on a scale of 1 to 5 ([see pages 15-17 in this document](https://www.fs.usda.gov/Internet/FSE_DOCUMENTS/fseprd536080.pdf)), indicating that bringing shared resources into the State will be difficult. California can't afford human-caused exacerbation of worsening natural fire seasons.

These types of occurrences - where extended adverse fire conditions follow significant natural ignition events - highlight the value of and need for robust, effective fire prevention programs. While the 2017 Thomas Fire and 2018 Camp Fire created intense pressure on public utilities to do more to mitigate wildfire risk from electrical equipment failures, v[ehicles and equipment operated by the general public remain major ignition source classes](https://www.latimes.com/business/la-fi-utility-wildfires-20171017-story.html). [Ongoing research](https://www.srs.fs.fed.us/pubs/gtr/gtr_srs171.pdf) supports the value of multifaceted approaches that target specific components of systems with mitigation efforts that are tailored to each component, such as education, engineering and enforcement.

Engineering mitigation efforts for wildfire prevention are generally the least understandable to the wildland fire professional community and the general public alike, and tend to be much less visible than other mitigations. Despite this, they can have profound benefits, such as how the introduction of [spark arresters](https://www.beckersupport.net/services/spark-arrester-qualification) contributed to the [virtual elimination of railroad-caused fires](https://www.hstoday.us/subject-matter-areas/infrastructure-security/railroads-can-teach-utilities-how-to-stop-causing-fires/) in the late 1800s. Engineering mitigation will lead the way in reducing electrical grid failure as a wildfire ignition source, but the recent [Apple Fire](https://thehill.com/changing-america/sustainability/environment/510401-car-diesel-is-behind-the-apple-wildfire-in) is yet another reminder of how much could still be accomplished if both existing and new engineering mitigtaions were implemented as broadly as possiblee.
